// Auto-generated by sync-pricing.ts
// Last updated: 2026-05-12T02:21:04.466Z
// DO NOT EDIT MANUALLY

export type BillingMode = "standard" | "batch" | "cache" | "long-context";

export interface PricingEntry {
  modelName: string;
  provider: string;
  billingMode: BillingMode;
  inputPrice: number;
  outputPrice: number;
  inputModality: "text" | "multimodal";
  outputModality: "text" | "multimodal";
  releaseDate: string;
  notes?: string;
}

export const pricingData: PricingEntry[] = [
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek-AI",
    "billingMode": "cache",
    "inputPrice": 0.0028,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-01-01",
    "notes": "CACHE HIT価格"
  },
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek-AI",
    "billingMode": "standard",
    "inputPrice": 0.14,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-01-01",
    "notes": "CACHE MISS価格"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek-AI",
    "billingMode": "cache",
    "inputPrice": 0.003625,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-01-01",
    "notes": "CACHE HIT価格、2026/05/31まで75%割引適用中"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek-AI",
    "billingMode": "standard",
    "inputPrice": 0.435,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-01-01",
    "notes": "CACHE MISS価格、2026/05/31まで75%割引適用中"
  }
];
