// Auto-generated by pipeline/generate-data-files.ts
// Last updated: 2026-05-13T00:56:15.425Z
// Source: SQLite database (pricing_entries table)
// DO NOT EDIT MANUALLY

export type BillingMode = "standard" | "batch" | "cache" | "long-context";

export interface PricingEntry {
  modelName: string;
  provider: string;
  billingMode: BillingMode;
  inputPrice: number;
  outputPrice: number;
  inputModality: "text" | "multimodal";
  outputModality: "text" | "multimodal";
  releaseDate: string;
  notes?: string;
}

export const pricingData: PricingEntry[] = [
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek-AI",
    "billingMode": "cache",
    "inputPrice": 0.0028,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュヒット時の入力価格"
  },
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek-AI",
    "billingMode": "standard",
    "inputPrice": 0.14,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュミス時の入力価格"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek-AI",
    "billingMode": "cache",
    "inputPrice": 0.003625,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュヒット時の入力価格。2026/05/31まで75%割引適用中"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek-AI",
    "billingMode": "standard",
    "inputPrice": 0.435,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュミス時の入力価格。2026/05/31まで75%割引適用中"
  },
  {
    "modelName": "Gemini 3.1 Flash ライブ プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.75,
    "outputPrice": 4.5,
    "inputModality": "multimodal",
    "outputModality": "multimodal",
    "releaseDate": "2026-05-13",
    "notes": "テキスト価格。音声・画像は分単位の課金あり"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "音声入力は0.25ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.45,
    "outputPrice": 2.7,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "優先度ティア。音声入力は0.90ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "音声入力は0.25ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.25,
    "outputPrice": 1.5,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "音声入力は0.50ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Pro プレビュー版",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 1,
    "outputPrice": 6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "プロンプト <= 200,000トークンの場合。超える場合は入力2.0/出力9.0ドル"
  },
  {
    "modelName": "Gemini 3.1 Pro プレビュー版",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 3.6,
    "outputPrice": 21.6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-13",
    "notes": "優先度ティア。プロンプト <= 20万トークンの場合"
  }
];
