// Auto-generated by pipeline/generate-data-files.ts
// Last updated: 2026-05-25T00:00:00.000Z
// Source: Cross-reference of leaderboard_scores + pricing_entries
// DO NOT EDIT MANUALLY

export interface ValueRankedModel {
  name: string;
  developer: string;
  slug: string;
  openSource: "open" | "closed" | "open-nc";
  type: "reasoning" | "foundation" | "chat" | "coder";
  compositeScore: number | null;
  inputPrice: number | null;
  outputPrice: number | null;
  valueScore: number | null;
  hle: number | null;
  sweBenchVerified: number | null;
  gpqaDiamond: number | null;
}

export const valueRankingData: ValueRankedModel[] = [];
